CREATE TABLE Hoja1(id DOUBLE,codigo DOUBLE,campo VARCHAR(10),energia VARCHAR(10),frecuencia VARCHAR(10),corriente VARCHAR(10),agente VARCHAR(10),Tecnica VARCHAR(10),patologias VARCHAR(10),protocolos VARCHAR(10),evidencia VARCHAR(10),tendencia VARCHAR(10),legal VARCHAR(10),consentimiento VARCHAR(10),indicaciones VARCHAR(10),contraindicaciones VARCHAR(10),equipos VARCHAR(10));
INSERT INTO Hoja1 (id,codigo,campo,energia,frecuencia,corriente,agente,Tecnica,patologias,protocolos,evidencia,tendencia,legal,consentimiento,indicaciones,contraindicaciones,equipos) VALUES 
(1,100000,'Terapia','','','','','','','','','','','','','',''),
(2,110000,'Terapia','Energía Electrica','','','','','','','','','','','','',''),
(3,111000,'Terapia','Energía Electrica','Baja Frecuencia','','','','','','','','','','','',''),
(4,111100,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','','','','','','','','','','',''),
(5,111110,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','Corriente Galvánica','','','','','','','','','',''),
(6,111120,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','Corriente Galvánica','Iontoforesis','','','','','','','','',''),
(7,111130,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','Corriente Galvánica','Electrolisis Percutánea','','','','','','','','',''),
(8,111140,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','Corriente Galvánica','tDCS','','','','','','','','',''),
(9,111150,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','Corriente Galvánica','Galvano-Palpación','','','','','','','','',''),
(10,111200,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','corrientes con componente Galvánico','','','','','','','','','',''),
(11,111210,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','corrientes con componente Galvánico','Corriente de Trabert','','','','','','','','',''),
(12,111220,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','corrientes con componente Galvánico','Corrientes Diadinámicas','','','','','','','','',''),
(13,111230,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','corrientes con componente Galvánico','Corriente de Leduc','','','','','','','','',''),
(14,111240,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','corrientes con componente Galvánico','Corrientes de Alto Voltaje','','','','','','','','',''),
(15,111300,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','Impulsos Aislados','','','','','','','','','',''),
(16,111310,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','Impulsos Aislados','Impulsos Cuadrangulares','','','','','','','','',''),
(17,111320,'Terapia','Energía Electrica','Baja Frecuencia','corriente Monofásica','Impulsos Aislados','Impulsos Triangulares','','','','','','','','',''),
(18,111200,'Terapia','Energía Electrica','Baja Frecuencia','corriente Bifásica','','','','','','','','','','',''),
(19,111210,'Terapia','Energía Electrica','Baja Frecuencia','corriente Bifásica','TENS','','','','','','','','','',''),
(20,111220,'Terapia','Energía Electrica','Baja Frecuencia','corriente Bifásica','NMES','','','','','','','','','',''),
(21,111230,'Terapia','Energía Electrica','Baja Frecuencia','corriente Bifásica','Microcorrientes','','','','','','','','','',''),
(22,112000,'Terapia','Energía Electrica','Media Frecuencia','','','','','','','','','','','',''),
(23,112100,'Terapia','Energía Electrica','Media Frecuencia','Corrientes sin Modular','','','','','','','','','','',''),
(24,112110,'Terapia','Energía Electrica','Media Frecuencia','Corrientes sin Modular','Continua','','','','','','','','','',''),
(25,112120,'Terapia','Energía Electrica','Media Frecuencia','Corrientes sin Modular','BMAC','','','','','','','','','',''),
(26,112121,'Terapia','Energía Electrica','Media Frecuencia','Corrientes sin Modular','BMAC','Corriente MegaA','','','','','','','','',''),
(27,112122,'Terapia','Energía Electrica','Media Frecuencia','Corrientes sin Modular','BMAC','Corriente de Kotz','','','','','','','','',''),
(28,112123,'Terapia','Energía Electrica','Media Frecuencia','Corrientes sin Modular','BMAC','Corrientes Aussie','','','','','','','','',''),
(29,112200,'Terapia','Energía Electrica','Media Frecuencia','Corrientes Moduladas','','','','','','','','','','',''),
(30,112210,'Terapia','Energía Electrica','Media Frecuencia','Corrientes Moduladas','Corrientes Interferenciales','','','','','','','','','',''),
(31,112211,'Terapia','Energía Electrica','Media Frecuencia','Corrientes Moduladas','Corrientes Interferenciales','Corrientes IF Tetrapolares','','','','','','','','',''),
(32,112212,'Terapia','Energía Electrica','Media Frecuencia','Corrientes Moduladas','Corrientes Interferenciales','Corrientes IF Bipolares','','','','','','','','',''),
(33,113000,'Terapia','Energía Electrica','Alta Frecuencia','','','','','','','','','','','',''),
(34,113110,'Terapia','Energía Electrica','Alta Frecuencia','Radiofrecuencia','','','','','','','','','','',''),
(35,120000,'Terapia','Energía Electromagnética','','','','','','','','','','','','',''),
(36,121000,'Terapia','Energía Electromagnética','Alta Frecuencia','','','','','','','','','','','',''),
(37,121100,'Terapia','Energía Electromagnética','Alta Frecuencia','Fototerapia','','','','','','','','','','',''),
(38,121110,'Terapia','Energía Electromagnética','Alta Frecuencia','Fototerapia','Infrarrojos','','','','','','','','','',''),
(39,121120,'Terapia','Energía Electromagnética','Alta Frecuencia','Fototerapia','LASER','','','','','','','','','',''),
(40,121121,'Terapia','Energía Electromagnética','Alta Frecuencia','Fototerapia','LASER','Baja Intesidad','','','','','','','','',''),
(41,121122,'Terapia','Energía Electromagnética','Alta Frecuencia','Fototerapia','LASER','Alta Intensidad','','','','','','','','',''),
(42,121130,'Terapia','Energía Electromagnética','Alta Frecuencia','Fototerapia','LED','','','','','','','','','',''),
(43,121200,'Terapia','Energía Electromagnética','Alta Frecuencia','MIcroondas','','','','','','','','','','',''),
(44,121300,'Terapia','Energía Electromagnética','Alta Frecuencia','Onda Corta','','','','','','','','','','',''),
(45,121310,'Terapia','Energía Electromagnética','Alta Frecuencia','Onda Corta','Capacitiva','','','','','','','','','',''),
(46,121320,'Terapia','Energía Electromagnética','Alta Frecuencia','Onda Corta','Inductiva','','','','','','','','','',''),
(47,121400,'Terapia','Energía Electromagnética','Alta Frecuencia','Magnetoterapia','','','','','','','','','','',''),
(48,121410,'Terapia','Energía Electromagnética','Alta Frecuencia','Magnetoterapia','Baja Intensidad','','','','','','','','','',''),
(49,121420,'Terapia','Energía Electromagnética','Alta Frecuencia','Magnetoterapia','Alta Intensidad','','','','','','','','','',''),
(50,121421,'Terapia','Energía Electromagnética','Alta Frecuencia','Magnetoterapia','Alta Intensidad','Sistemas INductivos','','','','','','','','',''),
(51,121422,'Terapia','Energía Electromagnética','Alta Frecuencia','Magnetoterapia','Alta Intensidad','Diamagnetoterapia','','','','','','','','',''),
(52,121423,'Terapia','Energía Electromagnética','Alta Frecuencia','Magnetoterapia','Alta Intensidad','RMN Terapéutica','','','','','','','','',''),
(53,121424,'Terapia','Energía Electromagnética','Alta Frecuencia','Magnetoterapia','Alta Intensidad','rTMS','','','','','','','','',''),
(54,121800,'Terapia','Energía Electromagnética','Alta Frecuencia','Hipertermia','','','','','','','','','','',''),
(55,130000,'Terapia','Energía Mecánica','','','','','','','','','','','','',''),
(56,131000,'Terapia','Energía Mecánica','Baja Frecuencia','','','','','','','','','','','',''),
(57,131100,'Terapia','Energía Mecánica','Baja Frecuencia','Vibradores','','','','','','','','','','',''),
(58,131110,'Terapia','Energía Mecánica','Baja Frecuencia','Vibradores','Manuales','','','','','','','','','',''),
(59,131120,'Terapia','Energía Mecánica','Baja Frecuencia','Vibradores','Vibra3','','','','','','','','','',''),
(60,131200,'Terapia','Energía Mecánica','Baja Frecuencia','Plataformas de Vibración','','','','','','','','','','',''),
(61,131300,'Terapia','Energía Mecánica','Baja Frecuencia','Deep Oscilation','','','','','','','','','','',''),
(62,132000,'Terapia','Energía Mecánica','Media Frecuencia','','','','','','','','','','','',''),
(63,132100,'Terapia','Energía Mecánica','Media Frecuencia','Sonoforesis','','','','','','','','','','',''),
(64,133000,'Terapia','Energía Mecánica','Alta Frecuencia','','','','','','','','','','','',''),
(65,133100,'Terapia','Energía Mecánica','Alta Frecuencia','Ultrasonidos (Terapéuticos)','','','','','','','','','','',''),
(66,133110,'Terapia','Energía Mecánica','Alta Frecuencia','Ultrasonidos (Terapéuticos)','Sonoforesis','','','','','','','','','',''),
(67,133120,'Terapia','Energía Mecánica','Alta Frecuencia','Ultrasonidos (Terapéuticos)','Terapia Combinada','','','','','','','','','',''),
(68,133200,'Terapia','Energía Mecánica','Alta Frecuencia','LIPUS','','','','','','','','','','',''),
(69,133300,'Terapia','Energía Mecánica','Alta Frecuencia','HIFUS','','','','','','','','','','',''),
(70,133400,'Terapia','Energía Mecánica','Alta Frecuencia','OPAF','','','','','','','','','','',''),
(71,200000,'Diagnostico','','','','','','','','','','','','','',''),
(72,210000,'Diagnostico','Energía Eléctrica','','','','','','','','','','','','',''),
(73,211000,'Diagnostico','Energía Eléctrica','Baja Frecuencia','','','','','','','','','','','',''),
(74,211100,'Diagnostico','Energía Eléctrica','Baja Frecuencia','Corriente Monofásicas','','','','','','','','','','',''),
(75,211110,'Diagnostico','Energía Eléctrica','Baja Frecuencia','Corriente Monofásicas','corriente Galvánica','','','','','','','','','',''),
(76,211111,'Diagnostico','Energía Eléctrica','Baja Frecuencia','Corriente Monofásicas','corriente Galvánica','Galvano-Palpación','','','','','','','','',''),
(77,211120,'Diagnostico','Energía Eléctrica','Baja Frecuencia','Corriente Monofásicas','Curvas IT/AT (Impulsos Aislados)','','','','','','','','','',''),
(78,211121,'Diagnostico','Energía Eléctrica','Baja Frecuencia','Corriente Monofásicas','Curvas IT/AT (Impulsos Aislados)','Impulsos Cuadrangulares','','','','','','','','',''),
(79,211122,'Diagnostico','Energía Eléctrica','Baja Frecuencia','Corriente Monofásicas','Curvas IT/AT (Impulsos Aislados)','Impulsos Triangulares','','','','','','','','',''),
(80,220000,'Diagnostico','Energía Mecánica','','','','','','','','','','','','',''),
(81,221000,'Diagnostico','Energía Mecánica','Baja Frecuencia','','','','','','','','','','','',''),
(82,221100,'Diagnostico','Energía Mecánica','Baja Frecuencia','Vibradores','','','','','','','','','','',''),
(83,222000,'Diagnostico','Energía Mecánica','Alta Frecuancia','','','','','','','','','','','',''),
(84,222100,'Diagnostico','Energía Mecánica','Alta Frecuancia','Ultrasonidos (Terapéuticos)','','','','','','','','','','',''),
(85,222110,'Diagnostico','Energía Mecánica','Alta Frecuancia','Ultrasonidos (Terapéuticos)','Terapia Combinada','','','','','','','','','',''),
(86,222200,'Diagnostico','Energía Mecánica','Alta Frecuancia','Ecografía','','','','','','','','','','','');